### ISSUE TITLE
The bean '***.FeignClientSpecification', defined in null, could not be registered. A bean with that nam

### ISSUE THREAD

**Issue by Albatronhenry** [Albatronhenry/SSM#2]
The bean '***.FeignClientSpecification', defined in null, could not be registered. A bean with that nam[1](https://blog.csdn.net/u012211603/article/details/84312709)|[2](https://blog.csdn.net/u012211603/article/details/84312709)

在application.yml中配置：
```yml
spring:
    # 多个接口上的@FeignClient(“相同服务名”)会报错，overriding is disabled。
   # 设置 为true ,即 允许 同名
  main:
    allow-bean-definition-overriding: true
```

在SpringBoot 2.1之前，这个配置默认就是true，而在2.1做了更改。
设置为true后，因为FeignClientSpecification的原因，FeignClient注解的configuration参数会被覆盖。
